### ISSUE TITLE
Remote IS Command Causes AssertionError

### ISSUE THREAD

**Issue by abythell** [angryelectron/xbmq-js#4]
Sending the JSON message:
```
{
	"type": 23,
	"destination64": "some-64-bit-address",
	"command": "IS"
}
```
To an xbmq request topic causes:
```
assert.js:89
  throw new assert.AssertionError({
  ^
AssertionError: Out of Original Buffer's Boundary
    at BufferReader.MAKE_NEXT_READER.BufferReader.(anonymous function) [as nextUInt8] (/usr/local/lib/node_modules/xbmq/node_modules/xbee-api/node_modules/buffer-reader/index.js:77:9)
    at Object.frame_parser.ParseIOSamplePayload (/usr/local/lib/node_modules/xbmq/node_modules/xbee-api/lib/frame-parser.js:206:29)
    at Object.frame_parser.(anonymous function) (/usr/local/lib/node_modules/xbmq/node_modules/xbee-api/lib/frame-parser.js:109:18)
    at XBeeAPI.parseFrame (/usr/local/lib/node_modules/xbmq/node_modules/xbee-api/lib/xbee-api.js:113:27)
    at XBeeAPI.parseRaw (/usr/local/lib/node_modules/xbmq/node_modules/xbee-api/lib/xbee-api.js:203:26)
    at XBeeAPI.<anonymous> (/usr/local/lib/node_modules/xbmq/node_modules/xbee-api/lib/xbee-api.js:133:10)
    at Object.SerialPort.opts.dataCallback (/usr/local/lib/node_modules/xbmq/node_modules/serialport/serialport.js:181:12)
    at SerialPortFactory.SerialPort._emitData (/usr/local/lib/node_modules/xbmq/node_modules/serialport/serialport.js:396:20)
    at afterRead (/usr/local/lib/node_modules/xbmq/node_modules/serialport/serialport.js:372:20)
    at /usr/local/lib/node_modules/xbmq/node_modules/serialport/serialport.js:388:9

```

**Comment by abythell** [comment]
jankolkmeier/xbee-api#37
